import type { ImageSourcePropType } from 'react-native';

export const icons = {
  arrowBack: require('../../assets/icons/arrow-back.png'),
  arrowBackWhite: require('../../assets/icons/arrow-back-white.png'),
  arrowRightWhite: require('../../assets/icons/arrow-right-white.png'),
  chevronRight: require('../../assets/icons/chevron-right.png'),
  chevronRightWhite: require('../../assets/icons/chevron-right-white.png'),
  mail: require('../../assets/icons/mail.png'),
  lock: require('../../assets/icons/lock.png'),
  lockConfirm: require('../../assets/icons/lock-confirm.png'),
  eye: require('../../assets/icons/eye.png'),
  plus: require('../../assets/icons/plus.png'),
  home: require('../../assets/icons/home.png'),
  recipes: require('../../assets/icons/recipes.png'),
  barcode: require('../../assets/icons/barcode.png'),
  barcodeLarge: require('../../assets/icons/barcode-large.png'),
  mapPin: require('../../assets/icons/map-pin.png'),
  user: require('../../assets/icons/user.png'),
  bookmark: require('../../assets/icons/bookmark.png'),
  bookmarkFilled: require('../../assets/icons/bookmark-filled.png'),
  bookmarkSaved: require('../../assets/icons/bookmark-saved.png'),
  help: require('../../assets/icons/help.png'),
  filter: require('../../assets/icons/filter.png'),
  star: require('../../assets/icons/star.png'),
  premium: require('../../assets/icons/premium.png'),
  warning: require('../../assets/icons/warning.png'),
  check: require('../../assets/icons/check.png'),
  clock: require('../../assets/icons/clock.png'),
  plate: require('../../assets/icons/plate.png'),
  flame: require('../../assets/icons/flame.png'),
  shieldCheck: require('../../assets/icons/shield-check.png'),
  lightbulb: require('../../assets/icons/lightbulb.png'),
  flashOff: require('../../assets/icons/flash-off.png'),
  allergenMilk: require('../../assets/icons/allergen-milk.png'),
  allergenEgg: require('../../assets/icons/allergen-egg.png'),
  allergenPeanut: require('../../assets/icons/allergen-peanut.png'),
  allergenTreeNuts: require('../../assets/icons/allergen-tree-nuts.png'),
  allergenGluten: require('../../assets/icons/allergen-gluten.png'),
  allergenSoy: require('../../assets/icons/allergen-soy.png'),
  allergenFish: require('../../assets/icons/allergen-fish.png'),
  allergenShellfish: require('../../assets/icons/allergen-shellfish.png'),
  prefLactoseFree: require('../../assets/icons/pref-lactose-free.png'),
  prefGlutenFree: require('../../assets/icons/pref-gluten-free.png'),
  prefVegetarian: require('../../assets/icons/pref-vegetarian.png'),
  prefVegan: require('../../assets/icons/pref-vegan.png'),
  prefNone: require('../../assets/icons/pref-none.png'),
  premiumBarcode: require('../../assets/icons/premium-barcode.png'),
  shieldOutline: require('../../assets/icons/shield-outline.png'),
  thumbsUp: require('../../assets/icons/thumbs-up.png'),
  creditCard: require('../../assets/icons/credit-card.png'),
  pix: require('../../assets/icons/pix.png'),
  boleto: require('../../assets/icons/boleto.png'),
  checkWhite: require('../../assets/icons/check-white.png'),
  categoryAll: require('../../assets/icons/category-all.png'),
  categoryHealthy: require('../../assets/icons/category-healthy.png'),
  categoryVegetarian: require('../../assets/icons/category-vegetarian.png'),
  categorySnacks: require('../../assets/icons/category-snacks.png'),
  categoryOther: require('../../assets/icons/category-other.png'),
  search: require('../../assets/icons/search.png'),
  chevronDown: require('../../assets/icons/chevron-down.png'),
} satisfies Record<string, ImageSourcePropType>;

export type IconName = keyof typeof icons;

export const images = {
  splashBackground: require('../../assets/images/splash-background.png'),
  splashLogo: require('../../assets/images/splash-logo.png'),
  welcomePhoto: require('../../assets/images/welcome-photo.png'),
  welcomeWave: require('../../assets/images/welcome-wave.svg'),
  backgroundPattern: require('../../assets/images/background-pattern.png'),
  logo: require('../../assets/images/logo.png'),
  loginWave: require('../../assets/images/login-wave.svg'),
  registerWave: require('../../assets/images/register-wave.svg'),
  terms: require('../../assets/images/terms.png'),
  privacy: require('../../assets/images/privacy.png'),
  onboardingWave: require('../../assets/images/onboarding-wave.png'),
  scannerFrame: require('../../assets/images/scanner-frame.png'),
  premiumIllustration: require('../../assets/images/premium-illustration.png'),
  unlockedConfetti: require('../../assets/images/unlocked-confetti.png'),
} as const;

export const allergenIcons = {
  milk: 'allergenMilk',
  egg: 'allergenEgg',
  peanut: 'allergenPeanut',
  tree_nuts: 'allergenTreeNuts',
  gluten: 'allergenGluten',
  soy: 'allergenSoy',
  fish: 'allergenFish',
  shellfish: 'allergenShellfish',
} as const satisfies Record<string, IconName>;

export const preferenceIcons = {
  lactose_free: 'prefLactoseFree',
  gluten_free: 'prefGlutenFree',
  vegetarian: 'prefVegetarian',
  vegan: 'prefVegan',
  none: 'prefNone',
} as const satisfies Record<string, IconName>;

export const CUSTOM_ALLERGY_ICON: IconName = 'plate';
