export const strings = {
  common: {
    networkError: 'Não foi possível conectar. Verifique sua internet e tente novamente.',
    unknownError: 'Algo deu errado. Tente novamente em instantes.',
    sessionExpired: 'Sua sessão expirou. Entre novamente.',
    retry: 'Tentar novamente',
    loading: 'Carregando…',
    offline: 'Você está sem conexão. Alguns conteúdos podem estar desatualizados.',
    empty: 'Nada por aqui ainda.',
    back: 'Voltar',
    close: 'Fechar',
    toggleSheet: 'Expandir ou recolher a lista',
    showPassword: 'Mostrar senha',
    hidePassword: 'Ocultar senha',
  },
  splash: {
    a11yLabel: 'Allivia',
    timeout: 'Não foi possível iniciar o aplicativo.',
  },
  welcome: {
    title: 'Seja bem vindo!',
    subtitle: 'Segurança em cada refeição.',
    descriptionBefore: 'O ',
    descriptionBrand: 'Allivia',
    descriptionAfter:
      ' ajuda você a conhecer melhor os alimentos e tomar decisões mais seguras para o seu dia a dia.',
    login: 'Fazer Login',
    noAccount: 'Não possui conta? ',
    register: 'Cadastre-se',
  },
  tabs: {
    home: 'Início',
    recipes: 'Receitas',
    scanner: 'Scanner',
    restaurants: 'Restaurantes',
    profile: 'Perfil',
  },
  auth: {
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Senha',
    confirmPlaceholder: 'Confirmar senha',
  },
  login: {
    title: 'Fazer login',
    subtitle: 'Faça login para continuar.',
    forgot: 'Recuperar senha',
    submit: 'Entrar',
  },
  register: {
    title: 'Fazer cadastro',
    subtitle: 'Cadastre-se para continuar.',
    termsLabel: 'Li e aceito os ',
    termsLink: 'Termos de uso',
    privacyLabel: 'Li e concordo com a ',
    privacyLink: 'Política de Privacidade',
    submit: 'Criar conta',
    ruleLength: '8 ou mais caracteres',
    ruleLetterNumber: 'Letra e número',
    goToLogin: 'Fazer login?',
    termsTitle: 'Termos de Uso',
    privacyTitle: 'Política de Privacidade',
  },
  forgot: {
    title: 'Recuperar senha',
    subtitle: 'Informe seu e-mail para receber as instruções.',
    submit: 'Enviar instruções',
    cooldown: (seconds: number) => `Aguarde ${seconds} s para enviar novamente.`,
  },
  requestSent: {
    title: 'Solicitação enviada!',
    message:
      'Caso o email informado esteja cadastrado, você receberá instruções para definir sua senha.',
    backToLogin: 'Voltar para login',
  },
  fieldErrors: {
    emailRequired: 'Informe seu e-mail.',
    emailInvalid: 'Informe um e-mail válido.',
    passwordRequired: 'Informe sua senha.',
    passwordWeak: 'A senha precisa ter 8 ou mais caracteres, com letra e número.',
    confirmRequired: 'Confirme sua senha.',
    confirmMismatch: 'As senhas não são iguais.',
  },
  authErrors: {
    invalidCredentials: 'E-mail ou senha incorretos.',
    invalidEmail: 'Informe um e-mail válido.',
    emailTaken: 'Já existe uma conta com este e-mail.',
    weakPassword: 'Escolha uma senha mais forte (mínimo 8 caracteres, com letra e número).',
    rateLimited: 'Muitas tentativas. Aguarde alguns minutos e tente novamente.',
    banned: 'Esta conta foi desativada. Fale com o suporte.',
    profileSave: 'Não foi possível salvar seus dados. Tente novamente.',
  },
  onboarding: {
    step: (n: number) => `Passo 0${n}`,
    nameTitle: 'Como podemos chamar você?',
    nameSubtitle: 'Necessário para personalizar sua experiência no Allivia',
    namePlaceholder: 'Nome ou apelido',
    continue: 'Continuar',
    allergiesTitle: 'Quais alergias você possui?',
    allergiesSubtitle: 'Selecione todas que se aplicam a você',
    addAllergy: 'Adicionar outra alergia',
    addAllergyTitle: 'Outra alergia',
    addAllergyPlaceholder: 'Ex.: mostarda',
    addAllergyConfirm: 'Adicionar',
    removeAllergy: (name: string) => `Remover ${name}`,
    advance: (n: number) => `Avançar (${n} ${n === 1 ? 'selecionada' : 'selecionadas'})`,
    preferencesTitle: 'Alguma restrição ou preferência?',
    preferencesSubtitle: 'Ajuda a otimizar nossas recomendações',
    none: 'Nenhuma',
    finish: 'Concluir',
  },
  nameErrors: {
    required: 'Informe como podemos chamar você.',
    tooShort: 'Use pelo menos 2 caracteres.',
    tooLong: 'Use no máximo 30 caracteres.',
    invalidChars: 'Use apenas letras, espaços, hífen e apóstrofo.',
  },
  customAllergyErrors: {
    tooShort: 'Use pelo menos 2 caracteres.',
    tooLong: 'Use no máximo 40 caracteres.',
    duplicate: 'Essa alergia já está na lista.',
    limit: 'Você pode adicionar até 5 alergias personalizadas.',
  },
  profile: {
    title: 'Meu perfil',
    edit: 'Editar',
    myRestrictions: 'Minhas restrições',
    noAllergies: 'Nenhuma alergia cadastrada',
    restrictionsRow: 'Restrições e preferências',
    restrictionsRowHint: 'Gerencie suas restrições e preferências',
    others: 'Outros',
    help: 'Ajuda e suporte',
    terms: 'Termos de uso',
    privacy: 'Privacidade e Segurança',
    logout: 'Sair da conta',
    deleteAccount: 'Excluir conta',
    avatar: 'Foto de perfil padrão',
  },
  editInfo: {
    title: 'Editar informações',
    name: 'Nome ou apelido',
    email: 'Email',
    newPassword: 'Nova senha (opcional)',
    currentPassword: 'Senha atual',
    currentPasswordHint: 'Para trocar e-mail ou senha, confirme sua senha atual.',
    save: 'Salvar',
    nameSaved: 'Informações atualizadas.',
    emailSent:
      'Enviamos um link de confirmação para o novo e-mail. A troca só vale após confirmar.',
    passwordSaved: 'Senha atualizada.',
  },
  editRestrictions: {
    title: 'Restrições e preferências',
    allergies: 'Alergias',
    preferences: 'Preferências',
    save: 'Salvar',
    saved: 'Restrições atualizadas.',
    discardTitle: 'Descartar alterações?',
    discardMessage: 'As mudanças que você fez não serão salvas.',
    discard: 'Descartar',
    keepEditing: 'Continuar editando',
  },
  deleteAccount: {
    title: 'Excluir conta',
    question: 'Tem certeza que deseja excluir sua conta?',
    warning: 'Esta ação não poderá ser desfeita',
    cancel: 'Cancelar',
    confirm: 'Excluir',
    passwordHint: 'Confirme sua senha para excluir a conta.',
    password: 'Senha',
  },
  help: {
    title: 'Ajuda e Suporte',
    email: 'alliviafood@gmail.com',
  },
  profileErrors: {
    wrongPassword: 'Senha atual incorreta.',
    reauthNeeded: 'Por segurança, confirme sua senha para continuar.',
    emailInUse: 'Este e-mail já está em uso.',
    saveFailed: 'Não foi possível salvar. Tente novamente.',
    deleteFailed: 'Não foi possível excluir sua conta agora. Tente novamente.',
  },
  recipes: {
    title: 'Receitas',
    subtitle: 'Encontre receitas seguras e deliciosas para o seu dia a dia',
    all: 'Todas',
    featured: 'Em destaque',
    more: 'Mais receitas para você',
    filters: 'Filtros',
    empty: 'Nenhuma receita encontrada com esses filtros.',
    clearFilters: 'Limpar filtros',
    loadError: 'Não foi possível carregar as receitas. Tente novamente.',
    offline: 'Você está sem conexão. Mostrando as receitas já carregadas.',
    minutes: (n: number) => `${n} min`,
    without: (labels: string[]) =>
      labels.length === 0 ? '' : `Sem ${labels.map((l) => l.toLowerCase()).join(', sem ')}`,
    save: 'Salvar receita',
    unsave: 'Remover dos salvos',
    saveError: 'Não foi possível salvar agora.',
    diets: {
      lactose_free: 'Sem lactose',
      gluten_free: 'Sem glúten',
      vegetarian: 'Vegetariana',
      vegan: 'Vegana',
    },
    richInProtein: 'Rica em proteínas',
  },
  recipeFilters: {
    title: 'Filtrar receitas 🔎',
    meal: 'Tipo de refeição',
    time: 'Tempo de preparo',
    diets: 'Preferências alimentares',
    ingredients: 'Ingredientes',
    include: 'Incluir ingredientes',
    exclude: 'Excluir ingredientes',
    add: (term: string) => `Adicionar ${term}`,
    remove: (term: string) => `Remover ${term}`,
    allergiesNote: 'Suas alergias serão consideradas automaticamente.',
    clear: 'Limpar',
    apply: 'Aplicar',
    close: 'Fechar filtros',
    errors: {
      tooShort: 'Use pelo menos 2 caracteres.',
      tooLong: 'Use no máximo 30 caracteres.',
      duplicate: 'Esse ingrediente já está na lista.',
      limit: 'Você pode adicionar até 5 ingredientes.',
    },
  },
  recipe: {
    back: 'Receitas',
    totalTime: 'Tempo total',
    serves: 'Rende',
    servings: (n: number) => `${n} ${n === 1 ? 'porção' : 'porções'}`,
    perServing: 'Por porção',
    kcal: (n: number) => `${n} kcal`,
    ingredients: 'Ingredientes',
    tipTitle: 'Dica Allivia',
    tipDefault:
      'Você pode variar os ingredientes de acordo com sua preferência e o que tiver disponível em casa!',
    steps: 'Modo de preparo',
    nutrition: 'Informações nutricionais (por porção)',
    calories: 'Calorias',
    protein: 'Proteínas',
    carbs: 'Carboidratos',
    fat: 'Gorduras',
    grams: (n: number) => `${n} g`,
    notFound: 'Não encontramos esta receita.',
    safe: 'Segura para você!',
    safeText: 'Esta receita não contém ingredientes que causam suas alergias:',
    danger: (labels: string[]) => `Atenção! Esta receita pode conter: ${labels.join(', ')}`,
    warning: 'Confira os ingredientes.',
    warningText: (labels: string[]) =>
      `Não conseguimos verificar automaticamente: ${labels.join(', ')}`,
    disclaimer:
      'Sempre leia os ingredientes e rótulos antes de consumir. O Allivia não substitui orientação de profissionais de saúde.',
  },
  saved: {
    title: 'Seus salvos',
    recipesTab: 'Receitas',
    restaurantsTab: 'Restaurantes',
    emptyRecipes: 'Todas as receitas salvas aparecerão aqui.',
    emptyRestaurants: 'Todos os restaurantes salvos aparecerão aqui.',
    removed: 'Receita removida',
    restaurantRemoved: 'Restaurante removido',
    undo: 'Desfazer',
  },
  home: {
    greeting: (name: string) => (name ? `Olá, ${name}! 👋` : 'Olá! 👋'),
    welcome: 'Que bom te ver por aqui!',
    scannerTitle: 'Scanner Allivia',
    scannerText: 'Identifique possíveis alergênicos nos alimentos com mais facilidade.',
    scannerButton: 'Ir para o Scanner',
    restrictions: 'Suas restrições',
    edit: 'Editar',
    recipesTitle: 'Receitas para você',
    recipesSubtitle: 'Selecionadas de acordo com a sua preferência',
    safeDescription: 'Simples, nutritivo e livre dos seus alergênicos',
    checkDescription: 'Confira os ingredientes',
    seeRecipe: 'Ver receita',
    noRecipe: 'Nenhuma receita disponível para o seu perfil no momento.',
    savedTitle: 'Restaurantes e receitas salvos',
    savedText: 'Confira os restaurantes e receitas salvos por você',
    premium: 'Recurso premium',
    restaurantsTitle: 'Restaurantes para você',
    restaurantsSubtitle: 'Opções que atendem às suas restrições',
  },
  scanner: {
    tip: 'Dica: posicione o alimento no centro e em um local bem iluminado',
    manual: 'Digitar código manualmente',
    torchOn: 'Ligar lanterna',
    torchOff: 'Desligar lanterna',
    permissionTitle: 'Precisamos da câmera para ler o código de barras dos produtos',
    permissionButton: 'Permitir câmera',
    permissionDenied:
      'Sem acesso à câmera não conseguimos ler o código. Você pode liberar nas configurações ou digitar o código.',
    openSettings: 'Abrir configurações',
    unavailable: 'Não foi possível acessar a câmera. Você pode digitar o código manualmente.',
    analyzing: 'Analisando produto…',
    invalidCode: 'Código inválido. Confira os números e tente de novo.',
    invalidData: 'Não conseguimos ler os dados deste produto. Tente outro.',
    notFound: 'Não encontramos este produto na nossa base.',
    code: (code: string) => `Código lido: ${code}`,
    scanAgain: 'Escanear novamente',
    typeOther: 'Digitar outro código',
    manualTitle: 'Digitar código',
    manualPlaceholder: 'Código de barras (8 a 14 números)',
    manualConfirm: 'Analisar',
    cameraLabel: 'Câmera lendo código de barras',
  },
  scanResult: {
    title: 'Resultado da análise',
    done: 'Concluído',
    contains: 'Atenção! Possíveis alergênicos para você:',
    warning: 'Confira o rótulo. Não foi possível confirmar:',
    safe: 'Nenhum alergênico do seu perfil foi encontrado nos ingredientes informados.',
    reasonMissing: 'dados incompletos do produto',
    reasonTrace: (label: string) => `pode conter ${label.toLowerCase()}`,
    reasonCustomFound: (term: string) => `${term} aparece nos ingredientes`,
    reasonCustomCheck: (term: string) => `Confira manualmente: ${term}`,
    otherIngredients: 'Outros ingredientes',
    noIngredients: 'Ingredientes não informados para este produto.',
    seeAll: 'Ver todos',
    productInfo: 'Informações do produto',
    category: 'Categoria',
    manufacturer: 'Fabricante',
    barcode: 'Código de barras',
    notInformed: 'Não informado',
    disclaimer:
      'A análise é um apoio e não substitui a leitura da embalagem. Confira sempre o rótulo antes de consumir.',
    backHome: 'Voltar para Home',
    productImage: 'Foto do produto',
  },
  restaurants: {
    title: 'Restaurantes',
    chooseAddress: 'Escolher endereço',
    changeAddress: 'Trocar endereço',
    searchPlaceholder: 'Buscar restaurantes ou culinária...',
    categories: {
      all: 'Todos',
      healthy: 'Saudáveis',
      vegetarian: 'Vegetariano',
      snacks: 'Lanches',
      other: 'Outros',
    },
    nearYou: 'Perto de você',
    meta: (cuisine: string, distance: string | null) =>
      distance ? `${cuisine} • ${distance}` : cuisine,
    rating: (value: string) => `Nota ${value}`,
    approximate:
      'Nenhum restaurante cobre todas as suas restrições. Mostrando os que mais se aproximam.',
    empty: 'Ainda não temos restaurantes cadastrados perto deste endereço.',
    noResults: 'Nenhum restaurante encontrado com essa busca.',
    needLocation: 'Escolha um endereço para ver restaurantes por perto.',
    mapUnavailable: 'O mapa aparece no aplicativo de celular.',
    mapLabel: 'Mapa com os restaurantes por perto',
    youAreHere: 'Você está aqui',
    save: 'Salvar restaurante',
    unsave: 'Remover dos salvos',
    saveError: 'Não foi possível salvar agora.',
    imageLabel: (name: string) => `Foto de ${name}`,
    location: {
      title: 'Localizar restaurantes',
      searchPlaceholder: 'Buscar endereço e número',
      search: 'Buscar endereço',
      useCurrent: 'Usar minha localização atual',
      currentFallback: 'Localização atual',
      currentHint: 'Toque para usar o GPS do aparelho',
      locating: 'Obtendo sua localização…',
      searching: 'Buscando endereço…',
      notFound: 'Endereço não encontrado. Confira o nome da rua e o número.',
      denied: 'Sem acesso à localização. Digite um endereço para ver restaurantes por perto.',
      unavailable: 'Não foi possível obter sua localização. Digite um endereço.',
      unsupported:
        'A busca por endereço funciona no aplicativo de celular. Aqui, use sua localização atual.',
      close: 'Fechar',
    },
    detail: {
      address: 'Endereço',
      covered: 'Opções sem os seus alergênicos',
      notCovered: 'Não informados pelo restaurante',
      none: 'Nenhum',
      confirmCustom: (terms: string) => `Confirme com o restaurante: ${terms}`,
      disclaimer:
        'Informações sobre alergênicos devem ser confirmadas diretamente com o restaurante antes de consumir.',
      route: 'Abrir rota no Google Maps',
      noRating: 'Sem nota',
    },
  },
  premium: {
    demoNotice: 'Ambiente de demonstração — nenhuma cobrança será feita.',
    title: 'Scanner Allivia',
    badge: 'Premium',
    subtitle: 'Identifique possíveis alergênicos nos alimentos de forma rápida e prática.',
    illustration: 'Celular lendo o código de barras de um pacote',
    benefits: [
      {
        icon: 'premiumBarcode',
        title: 'Identifique possíveis alergênicos',
        text: 'Leitura rápida dos ingredientes e alerta de alergênicos.',
      },
      {
        icon: 'shieldOutline',
        title: 'Mais segurança no dia a dia',
        text: 'Informações claras para você fazer escolhas seguras.',
      },
      {
        icon: 'thumbsUp',
        title: 'Prático e confiável',
        text: 'Tecnologia desenvolvida para facilitar sua rotina alimentar.',
      },
    ],
    choosePlan: 'Escolha o plano ideal para você',
    plans: {
      annual: {
        name: 'Plano Anual',
        price: 'R$49,90/ano',
        renewal: 'Cobrança única. Renova automaticamente em 1 ano.',
      },
      monthly: {
        name: 'Plano Mensal',
        price: 'R$9,90/mês',
        renewal: 'Renova automaticamente todo mês.',
      },
    },
    continue: 'Continuar',
  },
  payment: {
    title: 'Pagamento',
    summary: 'Resumo do pedido',
    planTitle: (plan: string) => `${plan} - Scanner Allivia`,
    method: 'Forma de pagamento',
    methods: { card: 'Cartão de crédito', pix: 'Pix', boleto: 'Boleto bancário' },
    cardData: 'Dados do cartão',
    number: 'Número do cartão',
    numberPlaceholder: '0000 0000 0000 0000',
    expiry: 'Validade',
    expiryPlaceholder: 'MM/AA',
    cvv: 'CVV',
    cvvPlaceholder: '123',
    simulatedOnly: 'Ambiente de demonstração: a confirmação será simulada.',
    footer: 'Ambiente de demonstração. Não digite dados de cartão reais.',
    confirm: 'Confirmar assinatura',
    errors: {
      number: 'Número de cartão inválido.',
      expiry: 'Validade inválida.',
      cvv: 'CVV inválido.',
      declined: 'Pagamento recusado (simulação). Tente outro cartão.',
      saveFailed: 'Não foi possível concluir a assinatura. Tente novamente.',
    },
  },
  premiumUnlocked: {
    title: 'Scanner desbloqueado!',
    text: 'Agora você tem acesso ilimitado ao nosso scanner premium.',
    start: 'Começar a usar',
    later: 'Talvez depois',
  },
} as const;
