insert into public.recipes
  (title, description, meal_types, ready_in_minutes, servings, ingredients, steps,
   allergens, diets, tip, allergens_reviewed, published, featured)
values

('Tapioca com banana e canela',
 'Café da manhã rápido, doce na medida e sem glúten.',
 '{breakfast,snack}', 10, 1,
 '{"3 colheres de sopa de goma de tapioca hidratada","1 banana-prata madura em rodelas","1 pitada de canela em pó"}',
 '{"Aqueça uma frigideira antiaderente em fogo médio, sem untar.","Espalhe a goma de tapioca peneirada, formando um disco fino e uniforme.","Quando a goma se firmar e soltar das bordas (cerca de 1 minuto), vire o disco.","Distribua a banana sobre metade do disco e polvilhe a canela.","Dobre ao meio, deixe aquecer por mais 30 segundos e sirva."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Peneire a goma antes de usar: assim a tapioca fica lisa e sem buracos.',
 false, false, false),

('Crepioca de tomate e orégano',
 'Mistura de ovo e tapioca, pronta em poucos minutos.',
 '{breakfast,snack}', 10, 1,
 '{"1 ovo","2 colheres de sopa de goma de tapioca hidratada","1 tomate pequeno picado sem sementes","1 pitada de sal","Orégano a gosto","1 fio de azeite"}',
 '{"Em uma tigela, bata o ovo com a goma de tapioca e o sal até ficar homogêneo.","Aqueça uma frigideira antiaderente com o fio de azeite em fogo médio.","Despeje a massa e espalhe por toda a frigideira.","Quando as bordas firmarem, vire e cozinhe o outro lado por 1 minuto.","Recheie com o tomate e o orégano, dobre ao meio e sirva."}',
 '{egg}', '{vegetarian,lactose_free,gluten_free}',
 'Para variar o recheio, use cenoura ralada ou espinafre refogado.',
 false, false, false),

('Mingau de aveia com banana',
 'Cremoso e quentinho, ideal para manhãs frias.',
 '{breakfast}', 10, 1,
 '{"200 ml de leite","3 colheres de sopa de aveia em flocos","1 banana pequena amassada","1 colher de chá de mel","1 pitada de canela em pó"}',
 '{"Em uma panela pequena, misture o leite, a aveia e a banana amassada.","Leve ao fogo baixo, mexendo sempre, por cerca de 5 minutos, até engrossar.","Desligue o fogo e adoce com o mel.","Sirva polvilhado com canela."}',
 '{milk,gluten}', '{vegetarian}',
 'A aveia comum pode ter contato com trigo no processamento; por isso esta receita é marcada com glúten.',
 false, false, false),

('Escondidinho de mandioca com carne moída',
 'Clássico brasileiro em versão sem leite e sem glúten.',
 '{lunch,dinner}', 50, 4,
 '{"800 g de mandioca descascada em pedaços","500 g de carne moída","1 cebola picada","2 dentes de alho picados","2 tomates picados","3 colheres de sopa de azeite","Sal e pimenta-do-reino a gosto","Cheiro-verde picado a gosto"}',
 '{"Cozinhe a mandioca em água com sal por cerca de 25 minutos, até ficar bem macia. Reserve 1 xícara da água do cozimento.","Amasse a mandioca ainda quente com 2 colheres de sopa de azeite e um pouco da água reservada, até formar um purê liso.","Em uma panela, aqueça o azeite restante e doure a cebola e o alho.","Junte a carne moída e refogue até perder a cor rosada. Acrescente os tomates, o sal e a pimenta e cozinhe por 10 minutos.","Desligue o fogo e misture o cheiro-verde.","Em um refratário, espalhe a carne e cubra com o purê de mandioca.","Leve ao forno preaquecido a 200 °C por 15 minutos, até dourar levemente."}',
 '{}', '{lactose_free,gluten_free}',
 'Para gratinar sem queijo, pincele um pouco de azeite sobre o purê antes de levar ao forno.',
 false, false, false),

('Frango com legumes',
 'Simples, nutritivo e cheio de cor.',
 '{lunch,dinner}', 30, 2,
 '{"1 colher de sopa de azeite de oliva","400 g de peito de frango em cubos","1/2 xícara de cenoura e batata em cubos pequenos","1/2 xícara de vagem em pedaços pequenos","1/2 xícara de pimentão vermelho e amarelo em cubos pequenos","1/2 xícara de couve-flor ou brócolis em buquês pequenos","2 folhas de repolho verde picadas grosseiramente","2 xícaras de água fervente","1 colher de sopa de cheiro-verde picado","Sal a gosto"}',
 '{"Em uma panela, aqueça metade do azeite em fogo alto. Junte o frango, tempere com sal e frite por 5 minutos, até dourar. Retire e reserve.","Na mesma panela, aqueça o azeite restante e refogue a cenoura, a batata, a vagem, os pimentões, a couve-flor ou o brócolis e o repolho até murcharem levemente.","Volte o frango à panela, junte a água fervente e misture.","Cozinhe em fogo médio por 10 minutos, até os legumes ficarem macios.","Desligue o fogo, polvilhe o cheiro-verde e sirva."}',
 '{}', '{lactose_free,gluten_free}',
 'Você pode variar os legumes de acordo com sua preferência e o que tiver disponível em casa!',
 false, false, true),

('Moqueca capixaba de peixe',
 'Moqueca tradicional do Espírito Santo, feita sem leite de coco.',
 '{lunch,dinner}', 40, 4,
 '{"800 g de postas de peixe branco (robalo, badejo ou pescada)","Suco de 1 limão","3 tomates maduros em rodelas","2 cebolas em rodelas","1 maço de coentro picado","1 colher de chá de colorau (urucum)","3 colheres de sopa de azeite","Sal a gosto"}',
 '{"Tempere as postas de peixe com o suco de limão e sal e deixe descansar por 15 minutos.","Em uma panela larga (de preferência de barro), regue o fundo com o azeite e misture o colorau.","Faça uma camada com metade da cebola e do tomate e metade do coentro.","Acomode as postas de peixe e cubra com o restante da cebola, do tomate e do coentro.","Tampe e cozinhe em fogo baixo por cerca de 20 minutos, sem mexer, apenas balançando a panela de vez em quando.","Confira o sal e sirva com arroz branco."}',
 '{fish}', '{lactose_free,gluten_free}',
 'Não mexa a moqueca com colher: balance a panela para o peixe não desmanchar.',
 false, false, false),

('Curry de grão-de-bico com espinafre',
 'Prato vegano, perfumado e rico em proteína vegetal.',
 '{lunch,dinner}', 30, 3,
 '{"2 xícaras de grão-de-bico cozido","2 xícaras de espinafre picado","1 cebola picada","2 dentes de alho picados","1 colher de chá de gengibre ralado","2 colheres de chá de curry em pó","3 tomates picados","1/2 xícara de água","2 colheres de sopa de azeite","Sal a gosto"}',
 '{"Em uma panela, aqueça o azeite e refogue a cebola até ficar transparente.","Junte o alho, o gengibre e o curry e mexa por 1 minuto, até perfumar.","Acrescente os tomates e cozinhe por 5 minutos, até formar um molho.","Adicione o grão-de-bico e a água e cozinhe em fogo baixo por 10 minutos.","Junte o espinafre, misture até murchar e acerte o sal.","Sirva com arroz."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Amasse algumas colheradas de grão-de-bico no próprio molho para deixá-lo mais encorpado.',
 false, false, false),

('Macarrão ao molho de tomate e manjericão',
 'Molho caseiro simples, pronto enquanto a massa cozinha.',
 '{lunch,dinner}', 25, 3,
 '{"250 g de macarrão de sêmola de trigo","5 tomates maduros picados","2 dentes de alho picados","3 colheres de sopa de azeite","Folhas de manjericão a gosto","Sal a gosto"}',
 '{"Cozinhe o macarrão em bastante água fervente com sal, conforme o tempo da embalagem. Escorra.","Enquanto isso, aqueça o azeite em uma frigideira e doure levemente o alho.","Junte os tomates e o sal e cozinhe em fogo médio por 10 minutos, amassando com a colher até formar um molho.","Misture o macarrão ao molho e finalize com as folhas de manjericão."}',
 '{gluten}', '{vegan,vegetarian,lactose_free}',
 'Confira o rótulo do macarrão: algumas marcas levam ovo na massa. Se levar, esta receita não serve para quem tem alergia a ovo.',
 false, false, false),

('Paçoca de amendoim caseira',
 'Doce junino feito com apenas quatro ingredientes.',
 '{snack,dessert}', 20, 8,
 '{"2 xícaras de amendoim torrado e sem pele","1 xícara de farinha de mandioca fina","1/2 xícara de açúcar","1 pitada de sal"}',
 '{"No processador, triture o amendoim até virar uma farofa úmida.","Junte a farinha de mandioca, o açúcar e o sal e pulse até a mistura ficar fina e grudar quando apertada.","Pressione a mistura com força em uma forma pequena forrada ou em forminhas.","Desenforme e corte em quadrados."}',
 '{peanut}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Se a mistura não firmar, processe mais um pouco: o óleo do amendoim é o que dá liga.',
 false, false, false),

('Bolo de cenoura com cobertura de chocolate',
 'O bolo de cenoura mais tradicional do Brasil.',
 '{dessert,snack}', 60, 12,
 '{"3 cenouras médias em pedaços","3 ovos","1/2 xícara de óleo","2 xícaras de açúcar","2 xícaras de farinha de trigo","1 colher de sopa de fermento químico em pó","Cobertura: 2 colheres de sopa de cacau em pó","Cobertura: 1 colher de sopa de manteiga","Cobertura: 3 colheres de sopa de açúcar","Cobertura: 3 colheres de sopa de leite"}',
 '{"Preaqueça o forno a 180 °C e unte uma forma com óleo e farinha de trigo.","No liquidificador, bata a cenoura, os ovos e o óleo até ficar liso.","Despeje em uma tigela, junte o açúcar e a farinha e misture bem.","Acrescente o fermento e misture delicadamente.","Asse por cerca de 40 minutos, até o palito sair limpo.","Para a cobertura, leve o cacau, a manteiga, o açúcar e o leite ao fogo baixo, mexendo até engrossar levemente.","Espalhe a cobertura sobre o bolo ainda morno."}',
 '{milk,egg,gluten}', '{vegetarian}',
 'Bata bem a cenoura no liquidificador para o bolo ficar fofinho e com cor bonita.',
 false, false, false);
