insert into public.recipes
  (title, description, meal_types, ready_in_minutes, servings, ingredients, steps,
   allergens, diets, tip, allergens_reviewed, published, featured)
values

('Ovos mexidos com tomate e cebolinha',
 'Proteína rápida para começar o dia.',
 '{breakfast}', 10, 1,
 '{"2 ovos","1 tomate pequeno picado sem sementes","1 colher de sopa de cebolinha picada","1 fio de azeite","1 pitada de sal"}',
 '{"Em uma tigela, bata levemente os ovos com o sal.","Aqueça o azeite em uma frigideira em fogo baixo e refogue o tomate por 1 minuto.","Junte os ovos e mexa devagar com uma espátula até ficarem cremosos.","Desligue o fogo, misture a cebolinha e sirva em seguida."}',
 '{egg}', '{vegetarian,lactose_free,gluten_free}',
 'Cozinhe em fogo baixo e desligue antes de secar: os ovos terminam de cozinhar com o calor da panela.',
 false, false, false),

('Pão de queijo de frigideira',
 'Versão rápida do pão de queijo, sem forno.',
 '{breakfast,snack}', 15, 2,
 '{"4 colheres de sopa de polvilho azedo","1 ovo","3 colheres de sopa de queijo meia cura ralado","2 colheres de sopa de leite","1 pitada de sal","1 fio de azeite"}',
 '{"Em uma tigela, misture o polvilho, o ovo, o queijo, o leite e o sal até formar uma massa mole.","Aqueça uma frigideira antiaderente untada com o azeite em fogo baixo.","Espalhe a massa, tampe e cozinhe por cerca de 4 minutos, até firmar.","Vire e doure o outro lado por mais 2 minutos. Sirva quente."}',
 '{milk,egg}', '{vegetarian,gluten_free}',
 'Confira o rótulo do polvilho: o produto puro não tem glúten.',
 false, false, false),

('Iogurte com granola caseira e frutas',
 'Granola feita na frigideira, crocante e pouco doce.',
 '{breakfast,snack}', 15, 2,
 '{"1 xícara de aveia em flocos","3 castanhas-do-pará picadas","2 colheres de sopa de uva-passa","1 colher de sopa de mel","1 pitada de canela em pó","2 potes de iogurte natural","1 banana em rodelas"}',
 '{"Em uma frigideira, toste a aveia e a castanha-do-pará em fogo baixo, mexendo, por cerca de 5 minutos.","Desligue o fogo, junte o mel, a canela e a uva-passa e misture bem. Deixe esfriar para ficar crocante.","Em dois copos, distribua o iogurte, a banana e a granola em camadas."}',
 '{milk,gluten,tree_nuts}', '{vegetarian}',
 'A granola fria pode ser guardada em pote fechado por até uma semana.',
 false, false, false),

('Cuscuz nordestino com tomate e cebola',
 'Cuscuz de milho macio, sem glúten e sem leite.',
 '{breakfast,dinner}', 20, 3,
 '{"2 xícaras de flocão de milho","1 xícara de água","1 colher de chá de sal","1 tomate picado","1/2 cebola picada","2 colheres de sopa de azeite"}',
 '{"Em uma tigela, misture o flocão, o sal e a água aos poucos, até a farinha ficar úmida e soltinha. Deixe hidratar por 10 minutos.","Coloque água no fundo da cuscuzeira, sem encostar na peneira, e leve ao fogo.","Acomode o flocão hidratado na peneira, sem apertar, tampe e cozinhe por cerca de 10 minutos após o vapor começar.","Enquanto isso, refogue o tomate e a cebola no azeite.","Sirva o cuscuz com o refogado por cima."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Não aperte o flocão na cuscuzeira: o vapor precisa passar para o cuscuz ficar fofo.',
 false, false, false),

('Smoothie de morango com banana',
 'Bebida gelada e cremosa, só com frutas.',
 '{breakfast,snack}', 5, 2,
 '{"1 banana congelada em rodelas","1 xícara de morangos","1 xícara de suco de laranja","Folhas de hortelã a gosto"}',
 '{"Lave bem os morangos e retire as folhas.","Bata todos os ingredientes no liquidificador até ficar cremoso.","Sirva em seguida."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Congele a banana já em rodelas: o smoothie fica cremoso sem precisar de gelo.',
 false, false, false),

('Arroz com brócolis',
 'Acompanhamento colorido para o dia a dia.',
 '{lunch,dinner}', 25, 4,
 '{"1 xícara de arroz branco","2 xícaras de água fervente","1 maço pequeno de brócolis em floretes","2 dentes de alho picados","2 colheres de sopa de azeite","Sal a gosto"}',
 '{"Em uma panela, aqueça o azeite e doure o alho.","Junte o arroz e refogue por 1 minuto.","Acrescente a água fervente e o sal e cozinhe em fogo baixo, com a panela semitampada, até a água quase secar.","Distribua os floretes de brócolis por cima, tampe e cozinhe por mais 5 minutos.","Desligue o fogo, misture delicadamente e sirva."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Os talos do brócolis também podem ir para o arroz: pique bem fininho e refogue junto com o alho.',
 false, false, false),

('Feijão carioca caseiro',
 'Feijão temperado e caldoso, base do prato brasileiro.',
 '{lunch,dinner}', 60, 6,
 '{"2 xícaras de feijão carioca","2 folhas de louro","1 cebola picada","3 dentes de alho amassados","2 colheres de sopa de azeite","Sal a gosto","Água"}',
 '{"Escolha e lave o feijão. Deixe de molho em água por pelo menos 8 horas e descarte a água.","Cozinhe o feijão na panela de pressão com água suficiente para cobrir dois dedos acima e as folhas de louro, por cerca de 25 minutos após pegar pressão.","Em outra panela, aqueça o azeite e doure a cebola e o alho.","Junte uma concha do feijão cozido, amasse e devolva tudo à panela do feijão.","Acerte o sal e cozinhe por mais 10 minutos em fogo baixo, até engrossar o caldo."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Espere a pressão sair totalmente antes de abrir a panela.',
 false, false, false),

('Strogonoff de frango',
 'Clássico cremoso para o almoço de família.',
 '{lunch,dinner}', 35, 4,
 '{"600 g de peito de frango em cubos","1 cebola picada","2 dentes de alho picados","2 colheres de sopa de extrato de tomate","1 caixa de creme de leite (200 g)","1 xícara de champignon fatiado","2 colheres de sopa de azeite","Sal a gosto"}',
 '{"Tempere o frango com sal.","Em uma panela, aqueça o azeite e doure o frango. Retire e reserve.","Na mesma panela, refogue a cebola e o alho.","Volte o frango, junte o extrato de tomate e o champignon e cozinhe por 10 minutos.","Desligue o fogo, misture o creme de leite e sirva com arroz."}',
 '{milk}', '{gluten_free}',
 'Não deixe ferver depois de colocar o creme de leite, para o molho não talhar.',
 false, false, false),

('Camarão ao alho e óleo',
 'Camarão dourado e perfumado, pronto em poucos minutos.',
 '{lunch,dinner}', 25, 3,
 '{"500 g de camarões médios limpos","5 dentes de alho fatiados","4 colheres de sopa de azeite","Suco de 1/2 limão","Salsinha picada a gosto","Sal a gosto"}',
 '{"Tempere os camarões com o suco de limão e sal.","Em uma frigideira grande, aqueça o azeite em fogo baixo e doure o alho, sem queimar.","Aumente o fogo, junte os camarões e salteie por 3 a 4 minutos, até ficarem rosados.","Finalize com a salsinha e sirva com arroz."}',
 '{shellfish}', '{lactose_free,gluten_free}',
 'Camarão cozido demais fica borrachudo: retire do fogo assim que ficar rosado.',
 false, false, false),

('Salmão assado com batatas e alecrim',
 'Prato completo assado em uma única assadeira.',
 '{dinner,lunch}', 40, 2,
 '{"2 filés de salmão (cerca de 300 g)","4 batatas pequenas em rodelas","2 ramos de alecrim","Suco de 1 limão","3 colheres de sopa de azeite","Sal a gosto"}',
 '{"Preaqueça o forno a 200 °C.","Em uma assadeira, misture as batatas com 2 colheres de sopa de azeite, sal e o alecrim. Asse por 20 minutos.","Tempere o salmão com sal e o suco de limão.","Afaste as batatas, coloque o salmão na assadeira e regue com o azeite restante.","Asse por mais 12 a 15 minutos, até o peixe soltar em lascas."}',
 '{fish}', '{lactose_free,gluten_free}',
 'Para batatas mais crocantes, seque bem as rodelas antes de temperar.',
 false, false, false),

('Yakisoba de legumes',
 'Macarrão oriental com legumes salteados.',
 '{dinner,lunch}', 30, 3,
 '{"250 g de macarrão para yakisoba","4 colheres de sopa de shoyu","1 colher de sopa de amido de milho","1 xícara de água","2 xícaras de repolho picado","1 cenoura em tiras","1 xícara de brócolis em floretes","1/2 pimentão vermelho em tiras","1 cebola em pétalas","2 colheres de sopa de óleo"}',
 '{"Cozinhe o macarrão conforme a embalagem, escorra e reserve.","Dissolva o amido de milho na água e misture o shoyu. Reserve.","Em uma frigideira grande ou wok, aqueça o óleo em fogo alto e salteie a cenoura, o brócolis e a cebola por 3 minutos.","Junte o repolho e o pimentão e salteie por mais 2 minutos.","Despeje o molho, mexa até engrossar e misture o macarrão. Sirva quente."}',
 '{gluten,soy,egg}', '{vegetarian,lactose_free}',
 'O shoyu comum leva trigo, e muitos macarrões para yakisoba levam ovo; por isso a receita marca Glúten, Soja e Ovo.',
 false, false, false),

('Tofu grelhado com legumes salteados',
 'Refeição vegana rica em proteína.',
 '{dinner,lunch}', 25, 2,
 '{"300 g de tofu firme em cubos","1 abobrinha em meias-luas","1 cenoura em rodelas finas","1/2 pimentão amarelo em tiras","2 dentes de alho picados","3 colheres de sopa de azeite","1 colher de chá de gergelim","Sal a gosto"}',
 '{"Seque bem o tofu com papel-toalha e tempere com sal.","Em uma frigideira antiaderente, aqueça 2 colheres de sopa de azeite e grelhe o tofu até dourar dos dois lados. Reserve.","Na mesma frigideira, aqueça o azeite restante e salteie o alho, a cenoura, a abobrinha e o pimentão por 5 minutos.","Volte o tofu, misture e finalize com o gergelim."}',
 '{soy}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Quanto mais seco o tofu, mais ele doura na frigideira.',
 false, false, false),

('Sopa de legumes com carne',
 'Sopa reconfortante para os dias frios.',
 '{dinner}', 45, 5,
 '{"400 g de músculo bovino em cubos","2 batatas em cubos","1 cenoura em cubos","1 chuchu em cubos","1 mandioquinha em cubos","1 cebola picada","2 dentes de alho picados","2 colheres de sopa de azeite","1,5 litro de água","Cheiro-verde picado a gosto","Sal a gosto"}',
 '{"Na panela de pressão, aqueça o azeite e doure a carne. Junte a cebola e o alho e refogue.","Acrescente a água e o sal e cozinhe por 20 minutos após pegar pressão.","Espere a pressão sair, abra a panela e junte os legumes.","Cozinhe sem pressão, em fogo médio, por cerca de 15 minutos, até os legumes ficarem macios.","Finalize com o cheiro-verde."}',
 '{}', '{lactose_free,gluten_free}',
 'Corte os legumes do mesmo tamanho para que cozinhem por igual.',
 false, false, false),

('Caldo verde',
 'Sopa portuguesa de batata e couve, muito popular no Brasil.',
 '{dinner}', 40, 4,
 '{"5 batatas médias em pedaços","1 cebola picada","2 dentes de alho picados","1 linguiça calabresa em rodelas finas","4 folhas de couve cortadas bem fininhas","1,2 litro de água","2 colheres de sopa de azeite","Sal a gosto"}',
 '{"Cozinhe as batatas com a cebola, o alho e a água por cerca de 20 minutos, até ficarem bem macias.","Bata tudo no liquidificador, com cuidado por estar quente, e volte à panela.","Em uma frigideira, doure a calabresa no azeite.","Junte a calabresa e a couve ao creme de batata e cozinhe por 3 minutos.","Acerte o sal e sirva."}',
 '{soy}', '{lactose_free,gluten_free}',
 'Linguiça calabresa industrializada pode levar proteína de soja e outros aditivos: a receita marca Soja por precaução. Confira o rótulo.',
 false, false, false),

('Salada de quinoa com legumes',
 'Salada fresca e completa, boa para levar na marmita.',
 '{lunch,dinner}', 25, 3,
 '{"1 xícara de quinoa","2 xícaras de água","1 pepino em cubos","2 tomates em cubos","1/2 cebola roxa picada","Salsinha picada a gosto","Suco de 1 limão","3 colheres de sopa de azeite","Sal a gosto"}',
 '{"Lave bem a quinoa em uma peneira.","Cozinhe a quinoa na água com uma pitada de sal por cerca de 15 minutos, até os grãos ficarem macios. Deixe esfriar.","Misture a quinoa com o pepino, o tomate, a cebola e a salsinha.","Tempere com o limão, o azeite e sal e sirva."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Lavar a quinoa antes de cozinhar tira o amargor natural do grão.',
 false, false, false),

('Hummus com palitos de cenoura',
 'Pasta de grão-de-bico para petiscar.',
 '{snack}', 10, 4,
 '{"2 xícaras de grão-de-bico cozido","2 colheres de sopa de tahine","Suco de 1 limão","1 dente de alho","3 colheres de sopa de azeite","3 colheres de sopa de água","Sal a gosto","2 cenouras em palitos"}',
 '{"No processador, bata o grão-de-bico, o tahine, o limão, o alho, o sal e a água até formar uma pasta lisa.","Com o processador ligado, acrescente o azeite aos poucos.","Sirva o hummus com os palitos de cenoura."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'O tahine é feito de gergelim, que não está no catálogo do app: quem tem alergia a gergelim deve evitar esta receita.',
 false, false, false),

('Pipoca de panela com páprica',
 'Lanche rápido e crocante.',
 '{snack}', 10, 3,
 '{"1/2 xícara de milho de pipoca","3 colheres de sopa de óleo","1 colher de chá de páprica doce","Sal a gosto"}',
 '{"Em uma panela grande, aqueça o óleo com 3 grãos de milho.","Quando os grãos estourarem, junte o restante do milho, tampe e agite a panela de vez em quando.","Quando os estouros ficarem espaçados, desligue o fogo.","Tempere com a páprica e o sal e misture."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Os 3 grãos de teste mostram a hora certa de colocar o restante do milho.',
 false, false, false),

('Brigadeiro de colher',
 'Doce brasileiro para comer de colher.',
 '{dessert}', 20, 6,
 '{"1 lata de leite condensado","2 colheres de sopa de cacau em pó","1 colher de sopa de manteiga"}',
 '{"Em uma panela, misture o leite condensado, o cacau e a manteiga.","Cozinhe em fogo baixo, mexendo sem parar, por cerca de 10 minutos, até desgrudar do fundo da panela.","Transfira para potinhos e sirva morno ou gelado."}',
 '{milk}', '{vegetarian,gluten_free}',
 'Use cacau em pó 100%: achocolatados podem conter soja e outros ingredientes.',
 false, false, false),

('Banana caramelizada com canela',
 'Sobremesa vegana feita na frigideira.',
 '{dessert}', 15, 2,
 '{"2 bananas-prata cortadas ao meio no comprimento","2 colheres de sopa de açúcar mascavo","1 pitada de canela em pó","3 colheres de sopa de suco de laranja"}',
 '{"Em uma frigideira antiaderente, espalhe o açúcar mascavo e leve ao fogo baixo até começar a derreter.","Junte o suco de laranja e mexa até formar uma calda.","Coloque as bananas e doure por 2 minutos de cada lado.","Polvilhe a canela e sirva com a calda."}',
 '{}', '{vegan,vegetarian,lactose_free,gluten_free}',
 'Bananas firmes, ainda não muito maduras, não desmancham na frigideira.',
 false, false, false),

('Arroz-doce',
 'Sobremesa cremosa e tradicional.',
 '{dessert}', 40, 6,
 '{"1 xícara de arroz branco","2 xícaras de água","1 litro de leite","1 xícara de açúcar","1 canela em pau","4 cravos-da-índia","Canela em pó para polvilhar"}',
 '{"Cozinhe o arroz na água com a canela em pau e os cravos até a água secar.","Junte o leite e o açúcar e cozinhe em fogo baixo, mexendo de vez em quando, por cerca de 25 minutos, até ficar cremoso.","Retire a canela em pau e os cravos.","Sirva morno ou gelado, polvilhado com canela em pó."}',
 '{milk}', '{vegetarian,gluten_free}',
 'O arroz-doce engrossa ao esfriar: desligue o fogo quando ainda estiver um pouco mole.',
 false, false, false);
