export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  screenHorizontal: 25,
  formHorizontal: 35,
  modalHorizontal: 27,
  inputIconLeft: 19,
  inputTextLeft: 50,
  tileGap: 12,
  progressGap: 9,
  headerTop: 6,
} as const;

export const sizes = {
  buttonHeight: 52,
  buttonSmallHeight: 38,
  inputHeight: 56,
  chipHeight: 29,
  tabBarHeight: 92,
  icon: 22,
  iconSmall: 15,
  iconInput: 23,
  iconButton: 25,
  iconBanner: 29,
  iconTab: 23,
  progressHeight: 5,
  checkboxWidth: 20,
  checkboxHeight: 18,
  filterButtonWidth: 33,
  filterButtonHeight: 31,
  iconBadgeSmall: 32,
  iconBadgeMedium: 56,
  iconBadgeLarge: 84,
  iconBadgeBenefit: 37,
  radio: 21,
  radioBorder: 2,
  iconPremiumBadge: 18,
  premiumBadgeHeight: 36,
  iconPayment: 29,
  badge: 16,
  badgeOffset: 6,
  border: 1,
  borderSelected: 2,
  iconBadgeIconRatio: 0.6,
  saveCircle: 34,
  touchTarget: 44,
  splashLogoWidth: 212,
  splashLogoHeight: 232,
  modalMaxHeight: 601,
  sheetHandleWidth: 41,
  sheetHandleHeight: 4,
  sheetHandleTop: 11,
} as const;
